server:
  port: 8080
  tomcat:
    basedir: ./temp
  servlet:
    session:
      timeout: 86400 #一天 60 * 60 * 24
spring:
  aop:
    auto: true
  datasource:
    url: jdbc:mysql://localhost:3306/pss?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

wechat:
  appid: wx26d99e2fd5647ca0
  appsecret: eb70ad9c6bb30d41a150d3448999e91b
  serviceToken: wangruitest